# Generated by Django 3.2.8 on 2022-03-03 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.PositiveIntegerField(unique=True)),
                ('nom_agence', models.CharField(max_length=200, null=True)),
                ('date_creation', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contribuable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=30)),
                ('identity', models.CharField(max_length=15)),
                ('nif', models.IntegerField(null=True, unique=True)),
                ('denomination', models.CharField(max_length=200)),
                ('is_owner', models.CharField(max_length=3)),
                ('quarter', models.CharField(max_length=50)),
                ('rue', models.CharField(max_length=200)),
                ('door_number', models.CharField(max_length=10)),
                ('parcel_number', models.CharField(max_length=20)),
                ('lot_number', models.CharField(max_length=20)),
                ('land_title_number', models.CharField(max_length=20)),
                ('tel', models.IntegerField(max_length=8)),
                ('longitude', models.CharField(blank=True, max_length=10)),
                ('latitude', models.CharField(blank=True, max_length=10)),
                ('geo_situation', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fs.agence')),
            ],
        ),
    ]
