# Generated by Django 3.2.8 on 2022-03-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuable',
            name='agence',
        ),
        migrations.AlterField(
            model_name='contribuable',
            name='tel',
            field=models.CharField(max_length=8),
        ),
    ]
