# Generated by Django 3.2.8 on 2022-03-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0002_auto_20220310_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuable',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
