# Generated by Django 3.2.8 on 2022-03-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0004_auto_20220310_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuable',
            name='photo_facade',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contribuable',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
