# Generated by Django 4.0.3 on 2022-03-24 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0005_auto_20220314_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuable',
            name='photo_profil',
        ),
    ]
