# Generated by Django 4.0.3 on 2022-03-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0006_remove_contribuable_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuable',
            name='photo_facade',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
